# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.
#
# If you want a smaller set of lints you can change this to specify
# 'package:lints/core.yaml'. These are just the most critical lints
# (the recommended set includes the core lints).
# The core lints are also what is used by pub.dev for scoring packages.

include: package:lints/recommended.yaml

plugins:
  prefer_shorthands: ^0.4.7

linter:
  rules:
    avoid_types_on_closure_parameters: true
    omit_local_variable_types: true
    unnecessary_this: true
    always_use_package_imports: true
    avoid_print: true
    collection_methods_unrelated_type: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_void_to_null: true
    prefer_single_quotes: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_annotating_with_dynamic: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catches_without_on_clauses: true
    avoid_classes_with_only_static_members: true
    avoid_field_initializers_in_const_classes: true
    prefer_expression_function_bodies: true
    one_member_abstracts: true
    avoid_slow_async_io: true
    avoid_web_libraries_in_flutter: true
    avoid_returning_this: true
    cascade_invocations: true
    implicit_call_tearoffs: true
    parameter_assignments: true
    prefer_constructors_over_static_methods: true
    prefer_null_aware_method_calls: true
    unnecessary_overrides: true
    use_to_and_as_if_applicable: true
    use_super_parameters: true
    sort_pub_dependencies: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    use_colored_box: true
    sized_box_for_whitespace: true
    avoid_unnecessary_containers: true
    matching_super_parameters: true
    no_default_cases: true
    directives_ordering: true
    require_trailing_commas: true

analyzer:
  exclude:
    - build/**
    - lib/generated/**
    - lib/**.freezed.dart
    - lib/**.g.dart
    - lib/**.config.dart
    - lib/generated_plugin_registrant.dart
    - lib/**.gr.dart
  errors:
    invalid_annotation_target: ignore
  enable-experiment:
    - dot-shorthands

dcm:
  rules:
    - avoid-assignments-as-conditions
    - avoid-cascade-after-if-null
    - avoid-casting-to-extension-type
    - avoid-collection-methods-with-unrelated-types
    - avoid-conditions-with-boolean-literals
    - avoid-double-slash-imports
    - avoid-duplicate-exports
    - avoid-duplicate-mixins
    - avoid-duplicate-named-imports
    - avoid-duplicate-test-assertions
    - avoid-empty-spread
    - avoid-explicit-pattern-field-name
    - avoid-generics-shadowing
    - avoid-global-state
    - avoid-missed-calls
    - avoid-misused-set-literals
    - avoid-nested-records
    - avoid-nullable-tostring
    - avoid-passing-self-as-argument
    - avoid-redundant-async
    - avoid-self-assignment
    - avoid-self-compare
    - avoid-substring
    - avoid-throw-in-catch-block
    - avoid-top-level-members-in-tests
    - avoid-unnecessary-conditionals
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
    - missing-test-assertion
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    - prefer-async-await
    - prefer-commenting-analyzer-ignores
    - prefer-conditional-expressions
    - prefer-correct-test-file-name
    - prefer-enums-by-name
    - prefer-first
    - prefer-immediate-return
    - prefer-iterable-of
    - prefer-last
    - avoid-commented-out-code
    - prefer-define-hero-tag
    - always-remove-listener
    - avoid-border-all
    - avoid-returning-widgets
    - avoid-shrink-wrap-in-lists
    - avoid-unnecessary-setstate
    - avoid-expanded-as-spacer
    - avoid-wrapping-in-padding
    - check-for-equals-in-render-object-setters
    - consistent-update-render-object
    - prefer-correct-edge-insets-constructor
    - prefer-extracting-callbacks
    - prefer-using-list-view
    - use-setstate-synchronously
    - avoid-incomplete-copy-with
    - avoid-unnecessary-stateful-widgets
    - avoid-missing-image-alt
    - prefer-text-rich
    - avoid-incorrect-image-opacity